### ISSUE TITLE
MGN12H Carriage CAD

### ISSUE THREAD

**Issue by bernhardberger** [nexx/Anycubic-Predator-Duet#1] opened 2020-04-06 12:18 UTC
Do you have the source for the MGN12H carriage by any chance? I think I'm seeing artefacts from the Belt running over the smooth idlers and I'd like to try a belt twist.

I would however need to move the belt Loop a few mm to the side and widen the gap for the backside so it doesn't rub..

**Comment by nexx** [comment] 2020-04-29 13:04
My sincere apologies for not seeing this sooner, for some reason I didn't get notification for the issue being posted. I'm happy to provide the carriage STEP file, I'll try and upload it later today or tomorrow. I do plan to redesign it in the near future to remove the need to use the stock carriage plate, but I haven't done that yet. I'll post again once I've uploaded the design for you :)

**Comment by bernhardberger** [comment] 2020-04-29 20:05
No worries. I've gotten myself some quality toothed 16T gates idlers from oozenest now, so the belt twist is no longer needed.

That being said: I would now like to get rid of the blue metal plate too, so that would actually come in handy ;-)

PS: have you designed the carriage for 16T pulleys or 20T? I'm thinking of changing to 16T pulleys when my Moons motors eventually arrive at some point. Just need to find a way to mount the 3mm dia 16T idlers..

**Comment by nexx** [comment] 2020-04-29 23:53
The carriages are made for a 20T gap, but the new version would be easy to create with a large enough gap for 16T or 20T :)

I'm using branded flanged bearings at the bottom. Something about those tiny bearings in the gates idlers makes me feel they won't last long and they're not cheap.

**Comment by bernhardberger** [comment] 2020-05-07 15:37
Yeah, I had problems with excessive vibrations on the belt from the flanged bearings, that's the reason why I went with toothed idlers. It's much more silent now and I think I also have a tad better surface finish because of it. I did however also change out the bolt for a new shoulder bolt that has a perfect fit.

The last missing piece right now would be new carriages, preferrably without the need for the blue plates for easier maintenance and less screws.. My current carriages developed some play already :/

**Comment by nexx** [comment] 2020-05-08 14:49
I apologise for not getting around to doing this yet :( It's still on my list of things to get done, I just haven't found the time yet.

**Comment by nexx** [comment] 2020-05-08 19:07
Working on this now. If you get a moment, can you measure the outside width of your GT2 belt when it's on a 16T pulley please? I don't have one handy to try with.

**Comment by bernhardberger** [comment] 2020-05-08 19:15
> Working on this now. If you get a moment, can you measure the outside width of your GT2 belt when it's on a 16T pulley please? I don't have one handy to try with.

https://forum.duet3d.com/topic/13572/delta-printer-belts-and-16-tooth-pulleys

I don't have any at hand either. I'm waiting for them to get stocked again at my usual supplier..

But in the Duet thread there should be all the info needed.

**Comment by nexx** [comment] 2020-05-09 00:29
Not finished yet, but here's a WIP image:
[https://imgur.com/a/zNcSQw1](https://imgur.com/a/zNcSQw1)

It's still a 2 part design, there's no way around it really with how close the belt is to the MGN12H carriage, but it should fit together securely without any play.

The rear part will have 2 varieties, one for 20T and one for 16T spacing. It means switching between them doesn't require a full reprint.

Will try and do some more work tomorrow, then will provide it if you want to test, or can hold off until I have tested it.

**Comment by bernhardberger** [comment] 2020-05-09 00:51
Count me in as an alpha/beta tester! That looks sweet! I love the compact form factor - this is almost exactly what I had in mind! I would need a version for 20T pulleys for now though (from the looks of the spacing between the belt and the M3 holes it looks like the 16T version?)

I do have one concern at first sight though: it will be really hard to get the belt through that last corner on the curl. I have tried this exact shape and I failed to bend my Gates/Unitta 2GT belt around that last corner where the teeth meet. In my experience this needs to be more open (flatter angle)

2 other little things to keep in mind:
1) I had the same idea of reducing the depth of the carriage as I didn't deem it necessary and it gets you some z-height and reduces the lever forces - BUT: even with the default depth the 440mm magball arms already are almost horizontal on the opposing edge of a tower. I didn't do any calculations yet - but reducing the depth may actually be problematic. I would however be open to just beta test that in realworld conditions. It's not often (probably never except for probing) that I go that far outside the center.

2) it might help if there is a 5mm-10mm "step" or something designed into the middle to fit the pieces together. That small of a gap should be easily bridgeable by almost any printer.
..I had to replace one of my carriages already as the holes for the M3 thread started to wear out. I wouldn't trust the screws alone to hold them firmly together long term.

**Comment by nexx** [comment] 2020-05-09 00:57
> Count me in as an alpha/beta tester! That looks sweet! I love the compact form factor - this is almost exactly what I had in mind! I would need a version for 20T pulleys for now though (from the looks of the spacing between the belt and the M3 holes it looks like the 16T version?)

We're off to a good start then! :) This is actually the 20T version.

> I do have one concern at first sight though: it will be really hard to get the belt through that last corner on the curl. I have tried this exact shape and I failed to bend my Gates/Unitta 2GT belt around that last corner where the teeth meet. In my experience this needs to be more open.

I'm using this exact design and spacing on my existing carriages. It holds the belts well and isn't too difficult to install, but we can tweak if needed.

> Point 1

Yeah I had the same thought, I'm was just toying around with it being a lower profile. Changing the depth of the front part is literally a 2 second job :)

> Point 2

You read my mind. already planned to assist with alignment and keep things from moving!

**Comment by bernhardberger** [comment] 2020-05-09 01:04
Perfect! It's also hard to judge from 2D pictures, so please forgive me. I just tried a similar design on my Igus drylinN mounts as I hooed it would hold the belt more firmly and I just couldn't get them bent enough.

PS: are you planning on using nuts to secure the magballs? Right now I'm using shaunppls version that screw directly into the plastic and the hold up extremely well: https://www.thingiverse.com/thing:4138445

Those magball mounts are by far the sturdiest and easiest to print (precisely) out there (I've tried them all). They haven't moved a micron and they came out perfect every time. The edged top also helped with print speed and surface finish, but that's probably just a matter of taste. I've had more problems with the ones using nuts than those. It probably helps that the mount has more flesh and can be printed directly on the plate and also doesn't bend as easily as those with overhangs and thinner design to fit the nuts. May be worth a shot..

**Comment by nexx** [comment] 2020-05-09 01:11
The current design uses nylon locking nuts, same as the original design by Haydn. I actually recreated his design in F360. It's on Thingiverse :) Personally I'd rather use the nuts because then the weight of the effector is clamped securely between the two faces of the plastic, but again, creating a version with smaller holes to allow screwing in directly wouldn't exactly be a chore :)

**Comment by bernhardberger** [comment] 2020-05-09 01:21
Last thing for today before going to bed: when moving the trigger plate forward because of the new depth - there won't be any space left for the flying extruder springs to screw into as they'll occupy the same space. Using the same screw to mount both also isn't a good option imho as the extruder will be pulling on it and the trigger height may become inconsistent.

One option that comes to my mind would be mounting the extruder spring from below (a hole on the bottom of the magball mount instead of on the top). Not the most convenient location, but I almost never undo them and with your design one could just unmount the the plate as a whole anyways

**Comment by nexx** [comment] 2020-05-09 11:28
I've published a version for you to test if you'd like? :) All of the mounting points for the flying extruder and endstop flag should match up with the stock positions but I haven't yet printed and tested it. Let me know what you think! [https://www.thingiverse.com/thing:4349266](https://www.thingiverse.com/thing:4349266)

**Comment by bernhardberger** [comment] 2020-05-09 12:13
Printing it right now :-)

**Comment by bernhardberger** [comment] 2020-05-09 18:06
Okay, I finished the first set and the 2 pieces fit together almost
perfectly and the screw holes are soot on.

However, exactly as I feared: I can't get the belt through the loop :/

The gap where the teeth meet is spot on, almost too loose, but the "island"
in the center turned out too big. Can't even get the belt in straight :/

Any change you can make the "island" in the loop any smaller and eventually
with a tiny bit more radius? I'm measuring about 1.00mm to 1.25mm on the
gap for the belt, but I think the Unitta 2GT are actually 1.38..?

I tried widening it with a cutter knife, but it's hopeless :/

**Comment by nexx** [comment] 2020-05-09 18:13
Got a pair of calipers handy? Could you fold the belt tooth to tooth and measure the thickness? and also just a single thickness of the belt as well.

Changing the size of the island is quick and easy, so don't worry about that :)

On the plus side, the modular nature means you only have to reprint the back part, not the whole thing.

Edit: Just double checked the CAD and I can confirm that gap is 1.5mm so it's possible it's being made smaller by the slicer or the machine is over extruding slightly. Either way, I can certainly widen it for you.

**Comment by bernhardberger** [comment] 2020-05-09 18:24
As requested see below. I also have measured the carriage I was using that fit the belt perfectly for comparison.

The gap for the backside also is a little bit on the narrow side, when running the belt through by hand there almost is no clearance and I fear that might end up in the belt rubbing if there are any sort of vibrations.

Let me know if I can measure anything else!

![IMG_20200509_202016](https://user-images.githubusercontent.com/2110083/81481777-bae7e080-9232-11ea-95e4-ddef108bca57.jpg)

![IMG_20200509_201956](https://user-images.githubusercontent.com/2110083/81481769-b0c5e200-9232-11ea-8b44-f94770a304fc.jpg)
![IMG_20200509_201946](https://user-images.githubusercontent.com/2110083/81481771-b3c0d280-9232-11ea-85d7-b64d8c75a862.jpg)
![IMG_20200509_202025](https://user-images.githubusercontent.com/2110083/81481774-b7545980-9232-11ea-887f-30df65f3b551.jpg)



![IMG_20200509_201824_1](https://user-images.githubusercontent.com/2110083/81481764-ad325b00-9232-11ea-97b8-fe032cd4a8b5.jpg)

![IMG_20200509_201800](https://user-images.githubusercontent.com/2110083/81481761-a6a3e380-9232-11ea-8e2a-54e6c162c05f.jpg),
![IMG_20200509_201901](https://user-images.githubusercontent.com/2110083/81481763-aa376a80-9232-11ea-8342-d258d6f4f295.jpg)



![IMG_20200509_201600](https://user-images.githubusercontent.com/2110083/81481757-a3a8f300-9232-11ea-8068-808e8e75a6f6.jpg)
![IMG_20200509_201516](https://user-images.githubusercontent.com/2110083/81481754-a0ae0280-9232-11ea-9beb-21bd7690c81f.jpg)

**Comment by nexx** [comment] 2020-05-09 18:25
That's perfect. Give me 5 minutes and I'll give you a new belt adaptor to try for fitment.

**Comment by bernhardberger** [comment] 2020-05-09 18:26
PS, a small pic for motivation: 

![IMG_20200509_202614](https://user-images.githubusercontent.com/2110083/81481870-59744180-9233-11ea-986b-a1c4ca3b2156.jpg)

Needs a bit of cleaning up, bit it fits like a glove :-)

**Comment by bernhardberger** [comment] 2020-05-09 18:28
> That's perfect. Give me 5 minutes and I'll give you a new belt adaptor to try for fitment.

No hurry, can't print anything anymore today.. baby is asleep about 2m from the printer. Wife will kill me if I do another printjob today :/

**Comment by nexx** [comment] 2020-05-09 18:29
> > That's perfect. Give me 5 minutes and I'll give you a new belt adaptor to try for fitment.
> 
> No hurry, can't print anything anymore today.. baby is asleep about 2m from the printer. Wife will kill me if I do another printjob today :/

No worries. I'll print one off here and check fitment. I'll likely publish two versions of each back eventually, with looser and tighter tolerances.

**Comment by bernhardberger** [comment] 2020-05-09 18:53
Not sure what's going on with the belts though. The Gates Unitta documents clearly show a height of 1.38mm.

And I also didn't order them from any unknown China sources, but from Oozenest in the UK (they ship faster to Austria and cheaper than even my local sources here or from Germany..) if not for Corona it would have been a 1 day delivery for 15 pounds..

**Comment by nexx** [comment] 2020-05-09 19:08
> Not sure what's going on with the belts though. The Gates Unitta documents clearly show a height of 1.38mm.
> 
> And I also didn't order them from any unknown China sources, but from Oozenest in the UK (they ship faster to Austria and cheaper than even my local sources here or from Germany..) if not for Corona it would have been a 1 day delivery for 15 pounds..

Very odd. Regardless, increasing the spacing isn't a big problem. I'll add a version to the thingiverse page shortly with a larger tolerance around the island and a slightly tighter one where the belt grips itself

**Comment by nexx** [comment] 2020-05-09 19:20
Uploaded a larger clearance version to Thingiverse. 10% increase around the island and a 5% reduction where the belt meshes to itself. Let me know how you get on with that one when it's convenient :)

**Comment by bernhardberger** [comment] 2020-05-10 09:28
![15891028164442256308137384880022](https://user-images.githubusercontent.com/2110083/81495538-312b2800-92b1-11ea-8e96-422ce47226cf.jpg)

(Very, very) Thight fit, but it works (had to fiddle around quite a bit to get it in) :-) ignore the botched up ironing job on top..

The spacing where the teeth meet is spot on, the shape of the loop still could be a mit more rounded to make it easier to fit the belt.

**Comment by nexx** [comment] 2020-05-10 11:03
Uploaded a new version for you:
- Clearance around the belt island increased just a little more
- Rounded the corners on the belt island

Everything else should be the same :)

**Comment by nexx** [comment] 2020-05-11 12:45
A little update. I've printed and tested a set of these here. I've found an issue where the moutning holes for the endstop "flag" are slightly too far forward preventing it from triggering. I'm going to update the design to have the holes in the right place and test again.

What I can say is the delta movement is a LOT smoother with this design, even with flange bearings on the tensioner.

**Comment by nexx** [comment] 2020-05-11 19:32
I've updated Thingiverse with the latest revision. I've tested this on my predator and it's working great! I've also provided a version with slightly larger tolerances for your bigger belts :)

**Comment by bernhardberger** [comment] 2020-05-11 19:35
Thank you very much! I'll print them tomorrow and give you some feedback, but the early revisions already looked very promising!

Also my Moons finally arrived today, so it's the perfect time to disassemble the whole thing anyways :-)

PS: I've already added some spacers to the endstops for my previous carriages, so I guess I'll probably be fine with the first revision. But nothing some superglue wouldn't fix in the worst case.. :-)

**Comment by bernhardberger** [comment] 2020-05-11 19:38
PS: please add a "buy me a beer" link or similar to your repo. You configs helped me a lot when trying to figure out my PA settings as my genuine BMG couldn't handle 3k E jerk and was stripping filament.

The carriages are now the icing on the top, you deserve some sponsored caffeine or malt :-)

**Comment by nexx** [comment] 2020-05-11 20:03
> Thank you very much! I'll print them tomorrow and give you some feedback, but the early revisions already looked very promising!
> 
> Also my Moons finally arrived today, so it's the perfect time to disassemble the whole thing anyways :-)

Fab! Excellent timing then! 

> PS: I've already added some spacers to the endstops for my previous carriages, so I guess I'll probably be fine with the first revision. But nothing some superglue wouldn't fix in the worst case.. :-)

The flag was 1mm too far forward due to a measurement error I made, doh! The version up there now has them in the right place. I also moved the flying extruder screw hole to the front, it works quite well.

> PS: please add a "buy me a beer" link or similar to your repo. You configs helped me a lot when trying to figure out my PA settings as my genuine BMG couldn't handle 3k E jerk and was stripping filament.
> 
> The carriages are now the icing on the top, you deserve some sponsored caffeine or malt :-)

I appreciate the offer, truly, but I just do this for fun and to mod my own machines. The fact others benefit from the work is just a great bonus!

Let me know how you get on, any issues and I'll happily make mods for you. Once you've tested and confirmed also, I'll post the source file to go with it.

FYI, I had my Predator throwing the extruder around at 500mm/s movement speeds with the new carriages, it was quite a sight! ;)

**Comment by bernhardberger** [comment] 2020-05-11 20:23
Yeah, I need to get new rails for that.. cheaped on on Machifit rails on Banggood and this still bites me.. can't get above 300 XY jerk or it ends in massive ringing, even with DDA tuned.. one has play, the other one binds and the third one was bent (twisted actually..).

Can you recommend any MGN12 rails besides original Hiwin (the only trustworthy Ali seller I know can't ship anything longer than 600mm to my country) and CNA rails (with the shipping they use it will take them months to arrive..).

Wouldn't mind any EU/UK source, but it's almost impossible to find 750mm or longer rails for a decent price anywhere..

**Comment by nexx** [comment] 2020-05-11 20:35
I actually purchased those same Machifit rails. They were binding when I got them but I completely rebuilt them and used professional grease on them. They're certainly not as quiet as genuine Hiwin, but they have been fine for my purposes. Genuine Hiwin rails would have cost more than I paid for the printer.

I wasn't printing at 500mm/s, just movement to make sure it was smooth and relatively quiet :)

**Comment by bernhardberger** [comment] 2020-05-11 21:14
You've got lucky then. I did clean them all out too and relubed them and 2 of them are running smooth now, but they have play (you can twist the carriage by hand and feel it, it also does a loud "click"ing noise on direction change) and the third one that doesn't have play in it has a bad carriage/balls that try to bind multiple times per circulation.. so there's no point in fixing the one carriage..

Would you mind sharing your current config.g? Seeing that we have mechanically similar machines (minus the cooling solution) I'd like to see if my values are completely off or actually realistic:

XY jerk of 300
XY Accel at 9k, (DDA around 44Hz - 50Hz, depending on the cooling mount and extruder)

E jerk 600 (anything above starts to strip filament and I get bulbs and underextrusion at > 0.2 PA, genuine Bondtech...)
PA: about 0.36 on a 30cm Capricorn XS / 0.15 on a 10cm Capricorn TL
E accel at 3k, 45mms retract and prime

I somehow can't believe when I look at other config.g files that people are running BMGs at 3k-6k Jerk.. same for the 3k XY jerk I see everywhere on the predator (but I'm sure my rails are a massive cause to this, as possibly my MagLev fans too as the bearings flop around a lot > 2k jerk, already got some ball bearing sunons on order..) 

.. if my values (especially for the extrusion) are completely unreasonable then I'll have to investigate.. not getting really consistent layers or stacking thereof.. at least I know it isn't the hotend as I have the same issues on a genuine e3d volcano/heatbreak/nozzle and their TriangleLabs counter

**Comment by nexx** [comment] 2020-05-11 21:42
I've just pushed my latest config to the repository for you :)

You mention problems with consistent layers. I had a similar problem and found it was due to friction from the stock spool holder. A quick way to test if this is the problem is to use a toilet tissue tube between the spool and the metal of the spool holder. I really need to print one using bearings but I haven't got around to doing that yet.

**Comment by bernhardberger** [comment] 2020-05-11 21:57
I've been running toilet paper spools for the past week as this was my suspicion to.. I then even "upgraded" to sneaker socks around the roll for even less friction, but didn't change anything.. 

Be aware that the Thingiverse design with the v-slot rollers doesn't fit on my spool holder (WAY too tight) - be sure to check dimensions before you print it. Same thing applied to the design that uses the predator's flange bearings.

If I find time tomorrow I may design something that works with the stock v-slot rollers as I like the idea of repurposing them.

I do however also play with the idea to just run a bowden tubing all the way to the flying extruder. That way you'd at least eliminate rapid jerking on the filament spool as you'd have a constant length between the extruder and the spool.

PS: very interesting that you're running your Delta BFBs at 500Hz PWM. I had to tune mine down to about 40Hz as even 100Hz ended in a very nasty high pitched sound.. in the end however I ditched them completely as they were vibrating excessively (I actually bought 4 of them as I wanted to use the other pair in another project, but they were vibrating badly too and I also couldn't find a good shroud for them)

**Comment by nexx** [comment] 2020-05-12 00:05
> I've been running toilet paper spools for the past week as this was my suspicion to.. I then even "upgraded" to sneaker socks around the roll for even less friction, but didn't change anything..
> 
> Be aware that the Thingiverse design with the v-slot rollers doesn't fit on my spool holder (WAY too tight) - be sure to check dimensions before you print it. Same thing applied to the design that uses the predator's flange bearings.

Good to know, thanks.

> If I find time tomorrow I may design something that works with the stock v-slot rollers as I like the idea of repurposing them.

I'd certainly be interested in seeing what you come up with :)

> I do however also play with the idea to just run a bowden tubing all the way to the flying extruder. That way you'd at least eliminate rapid jerking on the filament spool as you'd have a constant length between the extruder and the spool.

Also an interesting thought, might need to do some research into whether a reverse bowden of that length would cause any issue.

> PS: very interesting that you're running your Delta BFBs at 500Hz PWM. I had to tune mine down to about 40Hz as even 100Hz ended in a very nasty high pitched sound.. in the end however I ditched them completely as they were vibrating excessively (I actually bought 4 of them as I wanted to use the other pair in another project, but they were vibrating badly too and I also couldn't find a good shroud for them)

Weird. As far as I can tell mine have been fine and in fact they made more noise at a lower PWM. 500Hz seemed like the sweet spot. I'm actually debating putting my old BerdAir setup back on now that I understand how to get it set up better. The trouble is I have a tonne of projects and not enough time :P

**Comment by bernhardberger** [comment] 2020-05-14 08:14
I'm installing the carriages at the moment. Took a bit of filing the "secure pin" down to make them fit but it looks good so far. 

One suggestion though for the next time: make the "pin" a triangle or pentagon, didn't realize the design wasn't symmetric until I had the belts in, haha 🙈

PS: the only actual printing issue I have is that the holes on the "run through" side of the belt only have a thin-wall on the side of the slot (0.4mm LW). Had to reprint 2 of the 3 carriages as the hole broke out when inserting the M3 screws and applying a little pressure.

I looked up the previous designs and it's always been like that, I just didn't try to insert a screw in that hole at the previous attempts.

**Comment by bernhardberger** [comment] 2020-05-14 09:28
Okay, turns out the "clearance" version isn't tight enough after all. Belts are popping out under tension. Gonna reprint the default version.

**Comment by nexx** [comment] 2020-05-14 18:43
> I'm installing the carriages at the moment. Took a bit of filing the "secure pin" down to make them fit but it looks good so far.

The ones I printed snap together pretty well. Is it possible your printer is over-extruding slightly?

> One suggestion though for the next time: make the "pin" a triangle or pentagon, didn't realize the design wasn't symmetric until I had the belts in, haha 🙈

Good idea. It would serve the same purpose and also denote the upwards direction. Also, don't feel bad, I designed the thing and did EXACTLY the same on one tower :P 

> PS: the only actual printing issue I have is that the holes on the "run through" side of the belt only have a thin-wall on the side of the slot (0.4mm LW). Had to reprint 2 of the 3 carriages as the hole broke out when inserting the M3 screws and applying a little pressure.
>
> I looked up the previous designs and it's always been like that, I just didn't try to insert a screw in that hole at the previous attempts.

Not much I can do about that with the MGN12 rails and 20T spacing. The whole thing is a really tight fit as is. It should be fine though as the majority of the stress is taken by the upper and power part, not that single thickness wall.

> Okay, turns out the "clearance" version isn't tight enough after all. Belts are popping out under tension. Gonna reprint the default version.

Turns out the stock Predator belts are thinner than the spec, so they slip on the normal version. Not really relevant considering they're too short to use for the conversion anyway. I'm actually running generation 3 Gates GT2 belts.

Let me know if you hit any other issues and I'll do my best to tweak the design as needed. Getting the belts in the normal version is quite fiddly but it does work and there is zero slippage when they're in :)

**Comment by bernhardberger** [comment] 2020-05-14 19:32
All fine so far. It's possible that it's overextruding slightly, having some issues with PA on the Duet. Test prints and walls however always come out fine and soot on. My guess is that I was printing slightly too hot. They're mounted now and work excellently! It's immediately evident that there is a bunch of weight saved as the effector stopped dropping with the new carriages!

What pulleys are you using for the GT3 belts? Getting the belts wouldn't be a problem, already thought about that, but there are no "stock" pulleys from Gates that fit. Every supplier I contacted told me that they'd have to custom machine them - and that would run into triple figures for 3 pulleys.. don't want to use the "generic" 2GT pulleys as they have a slightly different tooth shape and Gates specifically advises against using them on < 40T.

The standard belts.. how are they too short? They're longer than the belts I'm using right now. I'm having less than 80cm from pulley to idler and a total length of under 160cm for the belt. I still can reach every part if the 380mm bed and even go outside of it. My 750mm rails are just as perfect as they get. Could possibly even go with 700mm if I'd like to cut it close.

PS: save yourself from buying Moons 0.9deg motors.. the Wantai 0.9° 2.4A probably are the most quiet and smoothest operating motors I've had (also tried the steppersonline 0.9 and had 1.8deg LDOs on loan). Imho the Wantai are the real deal. They also have less mechanical resistance than all the others and with the new carriages the effector now stayed in place when powered off. I think I'll be switching back to the Wantais at the weekend.. the sound and vibrations the Moons' are making is almost unbearable.. the only ones left that I could try are the ones that E3D is selling.. forgot the name of the manufacturer, but they almost look as good as the Wantai and Moons' on paper..

**Comment by nexx** [comment] 2020-05-14 20:28
> All fine so far. It's possible that it's overextruding slightly, having some issues with PA on the Duet. Test prints and walls however always come out fine and soot on. My guess is that I was printing slightly too hot. They're mounted now and work excellently! It's immediately evident that there is a bunch of weight saved as the effector stopped dropping with the new carriages!

Excellent! I'll likely scrap the slightly larger ones when properly publishing these then.

> What pulleys are you using for the GT3 belts? Getting the belts wouldn't be a problem, already thought about that, but there are no "stock" pulleys from Gates that fit. Every supplier I contacted told me that they'd have to custom machine them - and that would run into triple figures for 3 pulleys.. don't want to use the "generic" 2GT pulleys as they have a slightly different tooth shape and Gates specifically advises against using them on < 40T.

I'm using the stock pulleys from the machine and some branded flange bearings on the idlers. I initially thought the new belts were causing noise due to the differing tooth profile, but with the new carriages and being able to properly tension the belts, they're silent.

> The standard belts.. how are they too short? They're longer than the belts I'm using right now. I'm having less than 80cm from pulley to idler and a total length of under 160cm for the belt. I still can reach every part if the 380mm bed and even go outside of it. My 750mm rails are just as perfect as they get. Could possibly even go with 700mm if I'd like to cut it close.

Ah! I'm running 800mm rails which would explain why the stock belts ended up being too short. It limits how far up the idler can come before hitting the rail.

> PS: save yourself from buying Moons 0.9deg motors.. the Wantai 0.9° 2.4A probably are the most quiet and smoothest operating motors I've had (also tried the steppersonline 0.9 and had 1.8deg LDOs on loan). Imho the Wantai are the real deal. They also have less mechanical resistance than all the others and with the new carriages the effector now stayed in place when powered off. I think I'll be switching back to the Wantais at the weekend.. the sound and vibrations the Moons' are making is almost unbearable.. the only ones left that I could try are the ones that E3D is selling.. forgot the name of the manufacturer, but they almost look as good as the Wantai and Moons' on paper..

I actually swapped my Wantai steppers out when trying to reduce the noise. Now that I've solved that I may well put them back. I got a pack of 5 over a year ago and they really are great. My only complain is I wish they had connectors instead of a wire pigtail, I hate extending stepper cables :P

I've spent today redesigning the smart effector CAD I use so I can swap the Predator back to a volcano hotend and possibly the BerdAir pump I originally had on it.

**Comment by bernhardberger** [comment] 2020-05-14 21:21
> > All fine so far. It's possible that it's overextruding slightly, having some issues with PA on the Duet. Test prints and walls however always come out fine and soot on. My guess is that I was printing slightly too hot. They're mounted now and work excellently! It's immediately evident that there is a bunch of weight saved as the effector stopped dropping with the new carriages!
> 
> Excellent! I'll likely scrap the slightly larger ones when properly publishing these then.
> 
Yep. Scrap them. Sorry for the inconvenience. I actually ended up using 2 of the first batch you designed and one of the current. And you were right, the initial design of the belt loop was spot on. On the newest one I actually ended up putting cable ties on it for additional security. Sorry for steering you away from the initial design if the backplate. That was spot on.

> > What pulleys are you using for the GT3 belts? Getting the belts wouldn't be a problem, already thought about that, but there are no "stock" pulleys from Gates that fit. Every supplier I contacted told me that they'd have to custom machine them - and that would run into triple figures for 3 pulleys.. don't want to use the "generic" 2GT pulleys as they have a slightly different tooth shape and Gates specifically advises against using them on < 40T.
> 
> I'm using the stock pulleys from the machine and some branded flange bearings on the idlers. I initially thought the new belts were causing noise due to the differing tooth profile, but with the new carriages and being able to properly tension the belts, they're silent.
> 
> > The standard belts.. how are they too short? They're longer than the belts I'm using right now. I'm having less than 80cm from pulley to idler and a total length of under 160cm for the belt. I still can reach every part if the 380mm bed and even go outside of it. My 750mm rails are just as perfect as they get. Could possibly even go with 700mm if I'd like to cut it close.
> 
> Ah! I'm running 800mm rails which would explain why the stock belts ended up being too short. It limits how far up the idler can come before hitting the rail.
> 

That definitely explains it. If you're keen on saving another 5cm you can easily cut those Machifit rails with a bandsaw.. they're not even hardened and any metal blade goes through them like butter.. just ordered 3 rails from CNA on Ali, from what I'm reading on the Voron and BLV groups they should be lightyears ahead of the other clones.. time will tell. Would have gone "genuine" Hiwin from a reputable seller, but almost 200 EUR shipping to my country is just stupid..

> > PS: save yourself from buying Moons 0.9deg motors.. the Wantai 0.9° 2.4A probably are the most quiet and smoothest operating motors I've had (also tried the steppersonline 0.9 and had 1.8deg LDOs on loan). Imho the Wantai are the real deal. They also have less mechanical resistance than all the others and with the new carriages the effector now stayed in place when powered off. I think I'll be switching back to the Wantais at the weekend.. the sound and vibrations the Moons' are making is almost unbearable.. the only ones left that I could try are the ones that E3D is selling.. forgot the name of the manufacturer, but they almost look as good as the Wantai and Moons' on paper..
> 
> I actually swapped my Wantai steppers out when trying to reduce the noise. Now that I've solved that I may well put them back. I got a pack of 5 over a year ago and they really are great. My only complain is I wish they had connectors instead of a wire pigtail, I hate extending stepper cables :P
> 
> I've spent today redesigning the smart effector CAD I use so I can swap the Predator back to a volcano hotend and possibly the BerdAir pump I originally had on it.
 
Is the berd air really going to save that much weight? Can't think of a reason for needing more cooling than my two 5015 Sunons. They do come in at almost 60g compared to 20-ish for the Delta BFB though..

Right now I need a different solution for the effector mount. That metal plate was coming in at almost 100g, right now I scrapped it completely and screwed the X and Y springs directly into the BMG and the Z one is held by a cable tie around the motor.. lol

Does work fine with the filament pulling it up, but it's a bit top-heavy that way 🙈

![IMG_20200508_003318](https://user-images.githubusercontent.com/2110083/81987214-819be000-9639-11ea-925f-a22ca8d93ffa.jpg)
![IMG_20200508_003328](https://user-images.githubusercontent.com/2110083/81987222-852f6700-9639-11ea-8f4f-4f7bd4d42a6f.jpg)
![IMG_20200508_003313](https://user-images.githubusercontent.com/2110083/81987200-7cd72c00-9639-11ea-81c8-066379f53b38.jpg)

**Comment by nexx** [comment] 2020-05-14 22:18
> Yep. Scrap them. Sorry for the inconvenience. I actually ended up using 2 of the first batch you designed and one of the current. And you were right, the initial design of the belt loop was spot on. On the newest one I actually ended up putting cable ties on it for additional security. Sorry for steering you away from the initial design if the backplate. That was spot on.

No inconvenience at all. As I said before, I'm just happy to help out :) Plus this whole thing got me off my backside and cleared something off my todo list! :P

> That definitely explains it. If you're keen on saving another 5cm you can easily cut those Machifit rails with a bandsaw.. they're not even hardened and any metal blade goes through them like butter.. just ordered 3 rails from CNA on Ali, from what I'm reading on the Voron and BLV groups they should be lightyears ahead of the other clones.. time will tell. Would have gone "genuine" Hiwin from a reputable seller, but almost 200 EUR shipping to my country is just stupid..

It sounds like I really got lucky with the rails I have so I'm inclined to leave the whole thing alone as it won't give extra build volume or anything. In the future though, will definately look at either decently branded rails or second hand Hiwin from ebay. The 3 800mm rails only cost me £50 delivered and made a huge difference, so I'm happy.

FYI, just got done putting the Wantai steppers back on. I think all of my previous problems were down to non-straight belt paths. This thing is practically silent now. The Predator by default bends the belts on the stationary side due to a misalignment of the bracket the belts are bound to. It's something I discovered when I build the CAD model and honestly I'm shocked Anycubic never fixed it before production.

> Is the berd air really going to save that much weight? Can't think of a reason for needing more cooling than my two 5015 Sunons. They do come in at almost 60g compared to 20-ish for the Delta BFB though..

Probably not no but I'm wondering if part of the ringing and noise I got on fast moves was the fans flexing. I love the smart effector, but decent part cooling for it seems a bit of a challenge without everything wobbling around. Ironically it's one of the things I liked about the stock effector, it was a clever design.

Out of interest, do you have a link to the mount you are using? I have an abundance of 5015's kicking around I could try when I go back to a volcano.

> Right now I need a different solution for the effector mount. That metal plate was coming in at almost 100g, right now I scrapped it completely and screwed the X and Y springs directly into the BMG and the Z one is held by a cable tie around the motor.. lol
> 
> Does work fine with the filament pulling it up, but it's a bit top-heavy that way 🙈

I have been considering the possibility of adding a 4th axis to mount the extruder. Reprapfirmware supports it well, but it's yet another thing I haven't gotten around to.

**Comment by bernhardberger** [comment] 2020-05-14 22:37
I'm using his nozzles (fan shrouds)
https://www.thingiverse.com/thing:4251023

They're almost spot on. Over water the air makes a dent right below the nozzle. Could probably be about 2-3mm more to the back, but after about 10 iterations of my mounts I didn't have the nerve anymore to adjust them further. 


And my own beefed up version of the 5015 mount as his were flexing a lot and hitting the print / getting caught up on the infill - also the MagLev bearings didn't like the flexing around too much.. so I made these (Volcano):
https://www.thingiverse.com/thing:4333980

All in all it's an extremely quick print. If you're using genuine Sunon 5015s then you'll probably have to scale the nozzle up by 1-2% in X and Y as they have slightly bigger openings.

M3x12mm for fixing it (the holes should be just right for self-tapping).

Still using a 3010 on the original e3d shroud, just swapped the crappy fan for a silent 3010 V2 Sunon. Saves a ton of weight compared to the overengineered 4010 mounts.. it also allows you to mount the Volcano so that you have the nozzle on the front.

**Comment by bernhardberger** [comment] 2020-05-16 14:16
Oh, regarding your remote fan / berdair:

I have just found something I had bookmarked a while ago:
https://m.facebook.com/groups/1414240728624505?view=permalink&id=2136685553046682&sfnsn=mo

**Comment by nexx** [comment] 2020-05-16 22:44
Thanks for the info and sorry for not getting back to you sooner :)

I've published the final version of the design with both 20T and 16T versions. The only two changes of note are:
- Changed the "guide pin" to a triangle as suggested. Up means up :)
- Widened the right side for the belt pass through, both eliminating the thin wall and also allowing more room for the belt to it doesn't rub.

I'd like to credit you for your help if you wouldn't mind? Where would you like me to link to, your thingiverse account?

I'm planning to print the final version in ABS in the near future for my printer. I'll also upload the source file to thingiverse soon, just ran out of time tonight :)

Once again, thanks for all your testing and for giving me the kick in the backside to get this done at last :P

**Comment by nexx** [comment] 2020-05-22 19:49
I've added the source file for the carriage adaptor to the git. Closing this issue now.

Once again, thanks for all your help!

**Closed as completed by nexx** 2020-05-22 19:49 UTC
